version: "3.8"

services:
  100-jokes-service:
    build: 
      context: .
      dockerfile: dockerize/dockerfile
    image: 100jokes-service:latest
    container_name: 100jokes-service
    ports:
      - "8080:5000"
    networks:
      - Python-Flask-Network
networks:
  Python-Flask-Network:
